/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes1;


import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;

public class App {


    public static void main(String[] args) throws IOException {
//        Gson gson=new Gson();
//        Reader reader = Files.newBufferedReader(Paths.get("app/src/main/resources/data.json"));
//        BufferedReader readFromArray =new BufferedReader(reader);
//
//        Quotes[] convertArray = gson.fromJson(readFromArray, Quotes[].class);
//        int radnomQuote = (int)(Math.random()*(convertArray.length-1));
//        System.out.println("Name of Author: "+convertArray[radnomQuote].getAuthor());
//        System.out.println("The Quote : " + convertArray[radnomQuote].getText());
//        System.out.println("Quote number : " + radnomQuote);

        String url = "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
        sendGetRequest(url);
    }
    static void sendGetRequest(String urlString){
        try {
            URL url = new URL(urlString);
            HttpURLConnection connection = setUpConnectionObject(url);
            if(connection.getResponseCode() == 200){
                BufferedReader in = getBufferedReaderFromConnection(connection);
                printBufferedReaderContect(in);
                in.close();
            }
        } catch (MalformedURLException e) {
            System.out.println("Sorry, there was a problem creating the URL object,the error was:");
            System.out.println(e.getMessage());
            e.printStackTrace();
        } catch (IOException e) {
            System.out.println("Sorry, there was a problem opening the connection from the URL object, the error was:");
            System.out.println(e.getMessage());
            e.printStackTrace();
        }

    }

    static HttpURLConnection setUpConnectionObject(URL url) throws IOException {
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");
        connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");
        return connection;
    }

    static BufferedReader getBufferedReaderFromConnection(HttpURLConnection connection) throws IOException {
        InputStream inputStream = connection.getInputStream();
        InputStreamReader inputStreamReader = new InputStreamReader(inputStream);   // needs an input stream
        BufferedReader in = new BufferedReader(inputStreamReader);    // I need to provide the reader with a stream reader
        //  BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        return in;
    }

    static void printBufferedReaderContect(BufferedReader in) throws IOException {
        Gson gson=new Gson();
        ApiQuote convertArray = gson.fromJson(in,ApiQuote.class);
        System.out.println("Name of Author: "+convertArray.getQuoteAuthor());
        System.out.println("The Quote : " + convertArray.getQuoteText());
        File file = new File("app/src/main/resources/Apidata.txt");
        FileWriter fr = new FileWriter(file, true);
        BufferedWriter br = new BufferedWriter(fr);
        br.write(convertArray.toString()+"\n");

        br.close();
        fr.close();



    }
}